### ISSUE TITLE
Restrict scale on state comparison

### ISSUE THREAD

**Issue by byronwall** [epiforecasts/covid#66] opened 2020-05-21 20:25 UTC
It'd be nice if the comparative plot was limited to a maximum y axis value of 3 (similar to the other R plots).  Guam has been throwing things off for the last several updates:

![image](https://user-images.githubusercontent.com/495404/82602700-7b4cbd00-9b7f-11ea-9b25-f948899bf8b5.png)

**Comment by jhellewell14** [comment] 2020-07-18 19:01
Hello, thanks for flagging this. It looks like Guam has got slightly better over time and is no longer causing this. However, there does seem to be a general issue that reproduction number estimates are generally wider in places with fewer reported cases (even if this is as a result of their epidemic slowing down). We're going to be moving to a new model for estimating the reproduction number soon that we hope will iron out this problem ([EpiNow2](https://github.com/epiforecasts/EpiNow2/)).

Cheers,
Joel

**Closed by jhellewell14** 2020-07-18 19:01 UTC
