### ISSUE TITLE
Missing figures, Colors on figure 1 do not match key?

### ISSUE THREAD

**Issue by plodplodplod** [epiforecasts/covid#68] opened 2020-05-23 19:11 UTC
Missing figures 7 & 8.

On figure 1 the colors on map do not match key.
If the intensity/translucency is intended to indicate confidence, as in later figures, please add this to figure comment.

I can't see any variation in translucency on figures where it is stated that translucency does indicate confidence. Colors seem much less intense, but consistently so throughout each figure. This makes me think there is a mistake, or that the confidence should be stated in another way.

Layperson and colorblind, might simply be missing something that is obvious to intended audience.

**Comment by jhellewell14** [comment] 2020-07-18 19:02
Hello,
Could you link me to the page you are referring to please? Apologies for the slow response, we've been trying to sort out errors that have prevented us from updating :)
Cheers,
Joel

**Comment by gunnarkaestle** [comment] 2020-07-30 22:22
![grafik](https://user-images.githubusercontent.com/15989715/88979740-909e4000-d2c2-11ea-8dee-1c503bab77d3.png)

Maybe it is about: "Figure 1: Confirmed cases with date of infection on the 2020-07-11 and the time-varying estimate of the effective reproduction number (light bar = 90% credible interval; dark bar = the 50% credible interval.)."

The legend of figure 1 only includes colour schemes for 5 different categories, but not the two different credible intervals. One option to solve this is to include the light bars into the legend but this might be confusing as this may be hard to discriminate from the light/dark blue or orange/red difference. Another option is to use box plots with whiskers instead.

**Comment by seabbs** [comment] 2020-08-29 10:08
Thanks for exploring this - closing due to new approach + new vis coming soon.

**Closed by seabbs** 2020-08-29 10:08 UTC
