### ISSUE TITLE
National halving time for UK appears incompatible with regional ones?

### ISSUE THREAD

**Issue by PatParslow** [epiforecasts/covid#51] opened 2020-05-01 11:43 UTC
https://epiforecasts.io/covid/posts/national/united-kingdom/ shows regional halving times all -29 or higher, but national halving time is shown as -72 (-460 – -39) 
I haven't checked the calculations in the code, but that appears to suggest the two are calculated in different ways?

**Comment by steven-wooding** [comment] 2020-05-12 16:26
This also seems to be true of the Effective reproduction no (r) - the range estimate for the UK is 1.1 (range 1.1 - 1.2) where as HIGHEST of the sub-regions are estimated to have 1.0. It would be good to explain this discrepancy to avoid undermining confidence in the estimates.
This is particuarly relevant as it means the country as a whole is shown as 'Increasing' whereas none of the regions are.
<img width="594" alt="image" src="https://user-images.githubusercontent.com/7842018/81719883-8dd74000-9475-11ea-944b-c99451fb98ef.png">
<img width="499" alt="image" src="https://user-images.githubusercontent.com/7842018/81719940-a0ea1000-9475-11ea-8da5-ed574193ddd2.png">

**Comment by seabbs** [comment] 2020-08-29 10:19
Hi, 

Thanks for opening this issue and sorry for the delayed response. The difference is due to the differences in the data sources we are using. In the latest version of the estimates these issues should hopefully be mitigated so closing this for now.

**Closed by seabbs** 2020-08-29 10:19 UTC
