### ISSUE TITLE
State of Maine joins the UNBELIEVABLE data list....

### ISSUE THREAD

**Issue by dksia54** [epiforecasts/covid#186] opened 2021-12-02 19:08 UTC
The state of Maine in the United States has got to be WRONG.  An Rt of 5 with an exponential increase in cases in the hundreds of thousands just doesn't happen.

Once again -- does anyone in your organization ever look at the data and give it a sanity check?  As an engineer since 1976, I have always looked at data and asked myself, "can this be real?"

Iowa and Florida have been missing data for days, again as a result of someone's sloppy work.  Now we have Maine.

Please post credible data if you wish your site to remain credible.

**Comment by sbfnk** [comment] 2021-12-14 15:52
duplicate of #189

**Closed by sbfnk** 2021-12-14 15:52 UTC
Labels: duplicate
