### ISSUE TITLE
Website feedback

### ISSUE THREAD

**Issue by samclifford** [epiforecasts/covid#12] opened 2020-04-01 16:54 UTC
Overall I think this is great. Comments below are meant as helpful suggestions, not eviscerating the work that's been done.

- [x] Agree with @kathsherratt in #7 on colour. Greys are too similar, and I'm not sure that blue adequately represents that there are increasing cases. I don't think red-yellow-green is the right palette to use but colorbrewer's 3-class RdYlBu scheme is broadly interpretable as "bad", "not so bad", "good". The five-class scheme can be used for increasing, likely increasing, unsure, likely decreasing, decreasing, with grey reserved for "No data".

- [x] Equirectangular map projection is better than Mercator but you can probably ditch Antarctica and consider a separate plot for each of the World Bank's continent definitions, optionally splitting the Americas into South and "North and Central". There's too big a difference in variation in country area (both true and distorted) to just show all nations on the one map.

- [x] Figures 2 and 3 are missing, or relabelling has broken.

- [x] I assume that "likely increasing" has a median R0 > 1 but that 1 is outside the 50% and inside the 90% interval. This isn't confirmed on the page, though, and makes it a little difficult to interpret figures 1 and 4.

- [x] Using a different colour for the R0 estimates and the number of cases by date of infection would help make it clear to the reader that figures 5 (and 7) and 6 (and 8) show different things. The consistency of style is great, but the colouring can help identify that they're different. Please don't reuse the colours from the likely increasing/decreasing when doing this, though.

- [x] Caption for table 2 should go above, and might be worth putting in the note that when the doubling time estimate is "cases decreasing" that this corresponds to cases no longer doubling and hence the doubling time is effectively infinite. One way we got around this with the outbreak delay paper was to say "at least 4.5 days" rather than "4.5 - outbreak delayed".

Really great work.

**Comment by seabbs** [comment] 2020-04-01 17:53
Thanks for the comments - all broadly sensible (light edit to add tick boxes for gratification) 😅 . Will address tomorrow once some more people have had a chance to view.

**Comment by seabbs** [comment] 2020-04-01 21:19
" I assume that "likely increasing" has a median R0 > 1 but that 1 is outside the 50% and inside the 90% interval. This isn't confirmed on the page, though, and makes it a little difficult to interpret figures 1 and 4." is discussed in methods -> do you think this needs more highlighting elsewhere?

**Comment by seabbs** [comment] 2020-04-01 21:19
See https://github.com/epiforecasts/EpiNow/pull/35 for external changes

**Comment by seabbs** [comment] 2020-04-01 21:21
"Equirectangular map projection is better than Mercator but you can probably ditch Antarctica" -> I don't know anything about maps and I don't know what this means (obviously I know what ditching Antarctica means). Very happy to take a pull request, code is in `epiforecasts/EpiNow/R/global_map`

**Comment by seabbs** [comment] 2020-04-01 21:24
"Using a different colour for the R0 estimates and the number of cases by date of infection would help make it clear to the reader that figures 5 (and 7) and 6 (and 8) show different things. The consistency of style is great, but the colouring can help identify that they're different. Please don't reuse the colours from the likely increasing/decreasing when doing this, though." Colour choice here is foreshadowing the introduction of forecasts which will be differentiated from nowcasts using colour. As we want to make clear what is a nowcast and what is a forecast keen to keep the same across plots. Let me know if you think this is a mistake.

**Comment by seabbs** [comment] 2020-04-01 21:51
I've moved the map to a medium-term issue where we will look to do changes for v2. let me know if you feel this is essential for the first release.

**Comment by DidDrog11** [comment] 2020-04-02 06:51
In the figures showing RT over time "Confidence in the estimated values is indicated by shading with reduced shading" maybe clearer talking about transparency as shading may lead people to think about the confidence interval. 

For figures 7 & 8 is it possible to have an option to select specific countries or regions to look at. It's great being able to see the general trend so I think important to by default show all. However, perhaps would be a nice option to be able to pull out a couple specifically to look at their trends in comparison. 

For the subsequent pages the date in the top left might be misunderstood for when the models are run up to. Particularly if people don't click through to where it explicitly states it. 

I think it's a great site and visually very informative.

**Comment by seabbs** [comment] 2020-04-02 09:06
Thanks for the comments @DidDrog11. 

Date is when the models are run but because of the time shifts we are doing we don't have results until 9 days into the past (as looking at date of infection). Not sure how to make this clearer? 

Moved confidence point to short term issues to be addressed. 

Closed interactive figure suggestion and moved it into the medium term issue section . Good poitn

**Comment by samclifford** [comment] 2020-04-02 09:10
> " I assume that "likely increasing" has a median R0 > 1 but that 1 is outside the 50% and inside the 90% interval. This isn't confirmed on the page, though, and makes it a little difficult to interpret figures 1 and 4." is discussed in methods -> do you think this needs more highlighting elsewhere?
> 
> Okay with revisiting this.

Methods page is not a top level menu in the header, though. Ideally the caption would have enough information to understand what the plot is showing without necessarily going into how the results came about.

**Comment by samclifford** [comment] 2020-04-02 09:14
Also I've just noticed that the plot for Ukraine in figure 4 (not an issue in figure captioned "Cases by date of report (bars) and their estimated date of infection (light grey ribbon = 90% credible interval; dark grey ribbon = 50% credible interval) in all regions.") consists of only a handful of days that don't coincide with the week markers used. Might be worth putting minor tick marks for each day and ensuring that March 16 is always labelled. Alternatively, all plots could have the same x axis to allow more direct comparison of their time evolution. Lots of white space, sure, but perhaps a little more informative as it'll allow a more direct comparison of the rates of increase/decrease over time.

**Comment by seabbs** [comment] 2020-04-02 13:17
Adding detail to caption leading caption as requested. 

Added fix plot margins to medium term. One of those trivial things which is not trivial due to implementation. 

Closing as otherwise complete.

**Closed by seabbs** 2020-04-02 13:17 UTC
Labels: bug, enhancement
